name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.4
        env:
          QODANA_TOKEN: ${{ secrets.eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiIzSzZHbCIsInByb2plY3QiOiJwVmdHayIsInRva2VuIjoiQWFPN3EifQ.87v4H_cC50QhA2MfcK3p_YoUKQXGf-IdNZpcUeG-xWY }}
        with:
          args:--baseline,qodana.sarif.json